CREATE USER usr_siaag IDENTIFIED BY igeprev123;
GRANT CREATE SESSION TO usr_siaag;

CREATE TABLESPACE tbs_siaag DATAFILE
    SIZE 10 M
        AUTOEXTEND ON MAXSIZE UNLIMITED;

CREATE USER siaag IDENTIFIED BY siaag123
    DEFAULT TABLESPACE tbs_siaag
    QUOTA UNLIMITED ON tbs_siaag
    
    
