  CREATE TABLE "SIAAG"."TAB_ENDERECO" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
	"BAIRRO" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"CEP" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"CIDADE" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"COMPLEMENTO" VARCHAR2(200 CHAR), 
	"LOGRADOURO" VARCHAR2(200 CHAR) NOT NULL ENABLE, 
	"NUMERO" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"UF" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "PK_ENDERECO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_SIAAG"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_SIAAG" ;