DELETE FROM SIAAG.TAB_ENDERECO;
DELETE FROM SIAAG.TAB_PESSOA;
DELETE FROM SIAAG.TAB_USUARIO;
DELETE FROM SIAAG.TAB_PERFIL;

INSERT INTO SIAAG.TAB_PERFIL(ID,DESCRICAO) VALUES (1,'Administrador');
INSERT INTO SIAAG.TAB_PERFIL(ID,DESCRICAO) VALUES (2,'Recepcionista');
INSERT INTO SIAAG.TAB_PERFIL(ID,DESCRICAO) VALUES (3,'Atendente');
INSERT INTO SIAAG.TAB_PERFIL(ID,DESCRICAO) VALUES (4,'Usuario');

DELETE FROM SIAAG.TAB_TIPO_BENEFICIARIO;

