CREATE TABLE "SIAAG"."TAB_SETOR" 
   (	"ID" NUMBER(4,0) NOT NULL ENABLE, 
	"DESCRICAO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_TAB_SETOR" PRIMARY KEY ("ID")
   );

  CREATE UNIQUE INDEX "SIAAG"."UNQ_SETOR_DESCRICAO" ON "SIAAG"."TAB_SETOR" ("DESCRICAO");
  
  
  DELETE FROM SIAAG.TAB_SETOR;
  INSERT INTO SIAAG.TAB_SETOR(ID,DESCRICAO) VALUES (1,'Setor de Atendimento');