begin BEGIN EXECUTE IMMEDIATE 'ALTER TABLE SIAAG.TAB_ATENDIMENTO DROP COLUMN OBSERVACAO ';EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(SQLCODE||' -ERROR- '||SQLERRM);  END;end;
/
ALTER TABLE SIAAG.TAB_ATENDIMENTO ADD OBSERVACAO VARCHAR2(500) NULL
/