begin BEGIN EXECUTE IMMEDIATE 'ALTER TABLE SIAAG.TAB_HORARIO DROP COLUMN ATIVO ';EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(SQLCODE||' -ERROR- '||SQLERRM);  END;end;
/
ALTER TABLE SIAAG.TAB_HORARIO ADD ATIVO NUMBER(1) DEFAULT 1 NULL
/
DELETE FROM SIAAG.TAB_HORARIO WHERE ID IN (12,13)
/
INSERT INTO SIAAG.TAB_HORARIO(ID, HORARIO, ATIVO) VALUES (12, '01/01/2000 13:30:00', 0)
/
INSERT INTO SIAAG.TAB_HORARIO(ID, HORARIO, ATIVO) VALUES (13, '01/01/2000 14:00:00', 0)
/