CREATE OR REPLACE VIEW SIAAG.VW_PAINEL_ATENDIMENTO AS
  SELECT *
	FROM SIAAG.TAB_ATENDIMENTO AT
	WHERE AT.ATIVO = 1 AND AT.DATA = TO_DATE(sysdate) AND AT.ID_SITUACAO_ATENDIMENTO <> 4
	ORDER BY AT.DATA DESC, AT.ID_HORARIO_INICIO
/
	
begin BEGIN EXECUTE IMMEDIATE 'ALTER TABLE SIAAG.TAB_ATENDIMENTO DROP COLUMN TEMPO_ATENDIMENTO ';EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(SQLCODE||' -ERROR- '||SQLERRM);  END;end;
/
ALTER TABLE SIAAG.TAB_ATENDIMENTO ADD TEMPO_ATENDIMENTO NUMBER(10) NULL
/
begin BEGIN EXECUTE IMMEDIATE 'ALTER TABLE SIAAG.TAB_ATENDIMENTO DROP COLUMN INFORMACOES_ATENDIMENTO ';EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(SQLCODE||' -ERROR- '||SQLERRM);  END;end;
/
ALTER TABLE SIAAG.TAB_ATENDIMENTO ADD INFORMACOES_ATENDIMENTO VARCHAR2(500) NULL
/
begin BEGIN EXECUTE IMMEDIATE 'DROP TABLE SIAAG.TAB_ARQUIVO cascade constraints ';EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(SQLCODE||' -ERROR- '||SQLERRM);  END;end;
/
CREATE TABLE SIAAG.TAB_ARQUIVO
(
  ID NUMBER(10) GENERATED AS IDENTITY
    CONSTRAINT PK_ARQUIVO
    PRIMARY KEY,
  DESCRICAO VARCHAR2(100) NOT NULL,
  ARQUIVO BLOB NOT NULL,
  ID_ATENDIMENTO NUMBER(10) NOT NULL
  CONSTRAINT FK_ARQUIVO_ATENDIMENTO
  REFERENCES SIAAG.TAB_ATENDIMENTO
)
/