DELETE FROM SIAAG.TAB_ATENDIMENTO;

ALTER TABLE SIAAG.TAB_ATENDIMENTO MODIFY ID_HORARIO_INICIO DEFAULT NULL NULL;
ALTER TABLE SIAAG.TAB_ATENDIMENTO MODIFY ID_HORARIO_FIM DEFAULT NULL NULL;

ALTER TABLE SIAAG.TAB_ATENDIMENTO RENAME COLUMN DATA_INCLUSAO TO DATA_NAO_AGENDADO;
ALTER TABLE SIAAG.TAB_ATENDIMENTO MODIFY DATA_NAO_AGENDADO DEFAULT NULL NULL;

CREATE OR REPLACE VIEW SIAAG.VW_PAINEL_ATENDIMENTO AS
  SELECT *
	FROM SIAAG.TAB_ATENDIMENTO AT
	WHERE AT.ATIVO = 1 AND AT.DATA = TO_DATE(sysdate) AND AT.ID_SITUACAO_ATENDIMENTO <> 4
	ORDER BY AT.DATA DESC, AT.ID_HORARIO_INICIO;
