CREATE TABLE "SIAAG"."TAB_AGENDA" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE, 
	"ID_USUARIO" NUMBER(10,0) NOT NULL ENABLE, 
	"DATA" DATE NOT NULL ENABLE, 
	"ATIVO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	 CONSTRAINT "PK_AGENDA" PRIMARY KEY ("ID"))
/
  CREATE UNIQUE INDEX "SIAAG"."UNQ_DATA" ON "SIAAG"."TAB_AGENDA" ("DATA", "ID_USUARIO", "ATIVO")
  /