CREATE TABLE "SIAAG"."TAB_AGENDA_ITEM" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE  NOT NULL ENABLE, 
	"ID_AGENDA" NUMBER(10,0) NOT NULL ENABLE, 
	"TIPO_AGENDAMENTO" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"ID_HORARIO_INICIO" NUMBER(4,0) NOT NULL ENABLE, 
	"ID_HORARIO_FIM" NUMBER(4,0) NOT NULL ENABLE, 
	"ATIVO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	 CONSTRAINT "PK_AGENDA_ITEM" PRIMARY KEY ("ID"))
/
