CREATE TABLE "SIAAG"."TAB_BLOQUEIO_AGENDA" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE  NOT NULL ENABLE, 
	"DATA_INICIO" TIMESTAMP (6) NOT NULL ENABLE, 
	"DATA_FIM" TIMESTAMP (6) NOT NULL ENABLE, 
	"ID_HORARIO_INICIO" NUMBER(4,0) NOT NULL ENABLE, 
	"ID_HORARIO_FIM" NUMBER(4,0) NOT NULL ENABLE, 
	"ID_USUARIO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_BLOQUEIO_AGENDA" PRIMARY KEY ("ID"))
	 /

