ALTER TABLE TAB_ATENDIMENTO 
ADD (ID_USUARIO_CADASTROU NUMBER(10) NOT NULL);

ALTER TABLE TAB_ATENDIMENTO
ADD CONSTRAINT FK_ATENDIMENTO_ID_USU_INCLUSAO FOREIGN KEY
(
  ID_USUARIO_CADASTROU 
)
REFERENCES TAB_USUARIO
(
  ID 
)
ENABLE;

ALTER TABLE TAB_ATENDIMENTO 
RENAME CONSTRAINT TAB_ATENDIMENTO_FK1 TO FK_ATENDIMENTO_ID_ATENDENTE;

ALTER TABLE TAB_ATENDIMENTO 
RENAME CONSTRAINT TAB_ATENDIMENTO_FK2 TO FK_ATENDIMENTO_ID_HORARIO_FIM;