DELETE FROM SIAAG.TAB_HORARIO;
INSERT INTO SIAAG.TAB_HORARIO(ID,HORARIO) VALUES(1, '01/01/00 08:00:00,0000000');
INSERT INTO SIAAG.TAB_HORARIO(ID,HORARIO) VALUES(2, '01/01/00 08:30:00,0000000');
INSERT INTO SIAAG.TAB_HORARIO(ID,HORARIO) VALUES(3, '01/01/00 09:00:00,0000000');
INSERT INTO SIAAG.TAB_HORARIO(ID,HORARIO) VALUES(4, '01/01/00 09:30:00,0000000');
INSERT INTO SIAAG.TAB_HORARIO(ID,HORARIO) VALUES(5, '01/01/00 10:00:00,0000000');
INSERT INTO SIAAG.TAB_HORARIO(ID,HORARIO) VALUES(6, '01/01/00 10:30:00,0000000');
INSERT INTO SIAAG.TAB_HORARIO(ID,HORARIO) VALUES(7, '01/01/00 11:00:00,0000000');
INSERT INTO SIAAG.TAB_HORARIO(ID,HORARIO) VALUES(8, '01/01/00 11:30:00,0000000');
INSERT INTO SIAAG.TAB_HORARIO(ID,HORARIO) VALUES(9, '01/01/00 12:00:00,0000000');
INSERT INTO SIAAG.TAB_HORARIO(ID,HORARIO) VALUES(10, '01/01/00 12:30:00,0000000');
INSERT INTO SIAAG.TAB_HORARIO(ID,HORARIO) VALUES(11, '01/01/00 13:00:00,0000000');
INSERT INTO SIAAG.TAB_HORARIO (ID, HORARIO, ATIVO) VALUES (12, TO_TIMESTAMP('2000-01-01 13:30:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), 0);
INSERT INTO SIAAG.TAB_HORARIO (ID, HORARIO, ATIVO) VALUES (13, TO_TIMESTAMP('2000-01-01 14:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), 0);

DELETE FROM SIAAG.TAB_PERFIL;
INSERT INTO SIAAG.TAB_PERFIL (ID, DESCRICAO) VALUES (1, 'Administrador');
INSERT INTO SIAAG.TAB_PERFIL (ID, DESCRICAO) VALUES (2, 'Recepcionista');
INSERT INTO SIAAG.TAB_PERFIL (ID, DESCRICAO) VALUES (3, 'Atendente');
INSERT INTO SIAAG.TAB_PERFIL (ID, DESCRICAO) VALUES (4, 'Cliente');
INSERT INTO SIAAG.TAB_PERFIL (ID, DESCRICAO) VALUES (5, 'Técnico');

DELETE FROM SIAAG.TAB_PONTO_ATENDIMENTO_SETOR;
DELETE FROM SIAAG.TAB_SETOR;
INSERT INTO SIAAG.TAB_SETOR (ID, DESCRICAO, SIGLA) VALUES (1, 'Gabinete da Presidência', null);
INSERT INTO SIAAG.TAB_SETOR (ID, DESCRICAO, SIGLA) VALUES (2, 'Núcleo Gestor de Investimento', 'Nugin');
INSERT INTO SIAAG.TAB_SETOR (ID, DESCRICAO, SIGLA) VALUES (3, 'Assessoria de Comunicação', 'Ascom');
INSERT INTO SIAAG.TAB_SETOR (ID, DESCRICAO, SIGLA) VALUES (4, 'Controle Interno', 'CI');
INSERT INTO SIAAG.TAB_SETOR (ID, DESCRICAO, SIGLA) VALUES (5, 'Núcleo de Planejamento', 'Nuplan');
INSERT INTO SIAAG.TAB_SETOR (ID, DESCRICAO, SIGLA) VALUES (6, 'Núcleo de Arrecadação Financeira', 'Nuaf');
INSERT INTO SIAAG.TAB_SETOR (ID, DESCRICAO, SIGLA) VALUES (7, 'Procuradoria Jurídica', 'Projur');
INSERT INTO SIAAG.TAB_SETOR (ID, DESCRICAO, SIGLA) VALUES (8, 'Diretoria de Administração e Finanças', 'Dafin');
INSERT INTO SIAAG.TAB_SETOR (ID, DESCRICAO, SIGLA) VALUES (9, 'Gestão de Desenvolvimento de Pessoas', 'GDP');
INSERT INTO SIAAG.TAB_SETOR (ID, DESCRICAO, SIGLA) VALUES (10, 'Gerência de Orçamento e Finanças', 'Gerof');
INSERT INTO SIAAG.TAB_SETOR (ID, DESCRICAO, SIGLA) VALUES (11, 'Gerência de Administração e Serviços', 'Geras');
INSERT INTO SIAAG.TAB_SETOR (ID, DESCRICAO, SIGLA) VALUES (12, 'Núcleo de Tecnologia de Informação', 'Nuti');
INSERT INTO SIAAG.TAB_SETOR (ID, DESCRICAO, SIGLA) VALUES (13, 'Diretoria de Previdência', 'Dipre');
INSERT INTO SIAAG.TAB_SETOR (ID, DESCRICAO, SIGLA) VALUES (14, 'Gerência de Cadastro e Habilitação', 'Gecah');
INSERT INTO SIAAG.TAB_SETOR (ID, DESCRICAO, SIGLA) VALUES (15, 'Gerência de Concessão de Benefício', 'Gecob');
INSERT INTO SIAAG.TAB_SETOR (ID, DESCRICAO, SIGLA) VALUES (16, 'Núcleo de Registro de Contribuições', 'Nurc');
INSERT INTO SIAAG.TAB_SETOR (ID, DESCRICAO, SIGLA) VALUES (17, 'Central de Atendimento', 'Caten');
INSERT INTO SIAAG.TAB_SETOR (ID, DESCRICAO, SIGLA) VALUES (18, 'Serviço Social', null);
INSERT INTO SIAAG.TAB_SETOR (ID, DESCRICAO, SIGLA) VALUES (19, 'Núcleo de Diligências', 'Ndil');
INSERT INTO SIAAG.TAB_SETOR (ID, DESCRICAO, SIGLA) VALUES (20, 'Arquivo Geral', null);
INSERT INTO SIAAG.TAB_SETOR (ID, DESCRICAO, SIGLA) VALUES (21, 'Protocolo', null);

DELETE FROM SIAAG.TAB_SITUACAO_ATENDIMENTO;
INSERT INTO SIAAG.TAB_SITUACAO_ATENDIMENTO (ID, DESCRICAO) VALUES (1, 'Ativo');
INSERT INTO SIAAG.TAB_SITUACAO_ATENDIMENTO (ID, DESCRICAO) VALUES (2, 'Reagendado');
INSERT INTO SIAAG.TAB_SITUACAO_ATENDIMENTO (ID, DESCRICAO) VALUES (3, 'Expirado');
INSERT INTO SIAAG.TAB_SITUACAO_ATENDIMENTO (ID, DESCRICAO) VALUES (4, 'Cancelado');
INSERT INTO SIAAG.TAB_SITUACAO_ATENDIMENTO (ID, DESCRICAO) VALUES (5, 'Pré-atendimento');
INSERT INTO SIAAG.TAB_SITUACAO_ATENDIMENTO (ID, DESCRICAO) VALUES (6, 'Pré-atendido');
INSERT INTO SIAAG.TAB_SITUACAO_ATENDIMENTO (ID, DESCRICAO) VALUES (7, 'Atendido');


DELETE FROM SIAAG.TAB_TIPO_ATENDIMENTO;
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Aposentadoria', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Pensão', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Abono de Permanência', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('CTC ( Certidão de Tempo de Contribuição)', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Auxílio Funeral', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Isenção de Imposto de Renda', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Revisão de Aposentadoria', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Revisão de Pensão', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Reforma', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Reserva', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Reversão ao Serviço Ativo', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Retroativo de Benefício', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Inclusão no Rateio de Pensão', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Continuidade de Pensão', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Denúncia Diversas', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Declaração de Tempo Utilizado', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Restituição de Contribuição Previdenciária', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Salário Família', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Pensão Alimentícia', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Vantagens Pecuniárias', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Cópias de processos', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Liberação de credito', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Cadastro de conta corrente', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Atualização Cadastral', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Retificação de Dirf', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Comunicação de óbito', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Inclusão de dependentes', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Revisão de Reserva/Reforma', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Reativação de benefício', 30, 4, 0, 1);
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO (DESCRICAO, TEMPO_ATENDIMENTO, TEMPO_ANALISE, REDIRECIONAMENTO, ATIVO) VALUES ('Outros', 30, 4, 0, 1);

DELETE FROM SIAAG.TAB_TIPO_BENEFICIARIO;
INSERT INTO SIAAG.TAB_TIPO_BENEFICIARIO (ID, DESCRICAO) VALUES (1, 'Pensionista');
INSERT INTO SIAAG.TAB_TIPO_BENEFICIARIO (ID, DESCRICAO) VALUES (2, 'Público em geral');
INSERT INTO SIAAG.TAB_TIPO_BENEFICIARIO (ID, DESCRICAO) VALUES (3, 'Servidor ativo');
INSERT INTO SIAAG.TAB_TIPO_BENEFICIARIO (ID, DESCRICAO) VALUES (4, 'Servidor inativo');

DELETE FROM SIAAG.TAB_TIPO_REQUERENTE;
INSERT INTO SIAAG.TAB_TIPO_REQUERENTE (ID, DESCRICAO) VALUES (1, 'O próprio');
INSERT INTO SIAAG.TAB_TIPO_REQUERENTE (ID, DESCRICAO) VALUES (2, 'Curador');
INSERT INTO SIAAG.TAB_TIPO_REQUERENTE (ID, DESCRICAO) VALUES (3, 'Guardião');
INSERT INTO SIAAG.TAB_TIPO_REQUERENTE (ID, DESCRICAO) VALUES (4, 'Procurador');
INSERT INTO SIAAG.TAB_TIPO_REQUERENTE (ID, DESCRICAO) VALUES (5, 'Representante legal');
INSERT INTO SIAAG.TAB_TIPO_REQUERENTE (ID, DESCRICAO) VALUES (6, 'Tuto');

DELETE FROM SIAAG.TAB_USUARIO;
DELETE FROM SIAAG.TAB_PESSOA;
DELETE FROM SIAAG.TAB_PONTO_ATENDIMENTO;
DELETE FROM SIAAG.TAB_ENDERECO;
DELETE FROM SIAAG.TAB_PONTO_ATENDIMENTO_SETOR;
DELETE FROM SIAAG.TAB_PONTO_ATENDIMENTO;

INSERT INTO SIAAG.TAB_ENDERECO(BAIRRO, CEP, CIDADE, COMPLEMENTO, LOGRADOURO, NUMERO, UF) VALUES ('Nazaré','66040020', 'Belém', '', 'Avenida Alcindo Cacela', '1982', 'PA');
INSERT INTO SIAAG.TAB_ENDERECO(BAIRRO, CEP, CIDADE, COMPLEMENTO, LOGRADOURO, NUMERO, UF) VALUES ('Umarizal','66055200', 'Belém', 'Ed. Evolution, APT 705', 'Travessa Dom Romualdo de Seixas', '1476', 'PA');

INSERT INTO SIAAG.TAB_PONTO_ATENDIMENTO (NOME, ID_ENDERECO) VALUES ('IGEPREV BELÉM', (SELECT ID FROM SIAAG.TAB_ENDERECO WHERE CEP = '66040020' AND NUMERO = '1982'));

INSERT INTO SIAAG.TAB_PONTO_ATENDIMENTO_SETOR (ID_PONTO_ATENDIMENTO, ID_SETOR) VALUES ((SELECT ID FROM SIAAG.TAB_PONTO_ATENDIMENTO WHERE NOME = 'IGEPREV BELÉM'), (SELECT ID FROM SIAAG.TAB_SETOR WHERE DESCRICAO = 'Central de Atendimento'));
INSERT INTO SIAAG.TAB_PONTO_ATENDIMENTO_SETOR (ID_PONTO_ATENDIMENTO, ID_SETOR) VALUES ((SELECT ID FROM SIAAG.TAB_PONTO_ATENDIMENTO WHERE NOME = 'IGEPREV BELÉM'), (SELECT ID FROM SIAAG.TAB_SETOR WHERE DESCRICAO = 'Gabinete da Presidência'));
INSERT INTO SIAAG.TAB_PONTO_ATENDIMENTO_SETOR (ID_PONTO_ATENDIMENTO, ID_SETOR) VALUES ((SELECT ID FROM SIAAG.TAB_PONTO_ATENDIMENTO WHERE NOME = 'IGEPREV BELÉM'), (SELECT ID FROM SIAAG.TAB_SETOR WHERE DESCRICAO = 'Núcleo Gestor de Investimento'));
INSERT INTO SIAAG.TAB_PONTO_ATENDIMENTO_SETOR (ID_PONTO_ATENDIMENTO, ID_SETOR) VALUES ((SELECT ID FROM SIAAG.TAB_PONTO_ATENDIMENTO WHERE NOME = 'IGEPREV BELÉM'), (SELECT ID FROM SIAAG.TAB_SETOR WHERE DESCRICAO = 'Assessoria de Comunicação'));
INSERT INTO SIAAG.TAB_PONTO_ATENDIMENTO_SETOR (ID_PONTO_ATENDIMENTO, ID_SETOR) VALUES ((SELECT ID FROM SIAAG.TAB_PONTO_ATENDIMENTO WHERE NOME = 'IGEPREV BELÉM'), (SELECT ID FROM SIAAG.TAB_SETOR WHERE DESCRICAO = 'Controle Interno'));
INSERT INTO SIAAG.TAB_PONTO_ATENDIMENTO_SETOR (ID_PONTO_ATENDIMENTO, ID_SETOR) VALUES ((SELECT ID FROM SIAAG.TAB_PONTO_ATENDIMENTO WHERE NOME = 'IGEPREV BELÉM'), (SELECT ID FROM SIAAG.TAB_SETOR WHERE DESCRICAO = 'Núcleo de Planejamento'));
INSERT INTO SIAAG.TAB_PONTO_ATENDIMENTO_SETOR (ID_PONTO_ATENDIMENTO, ID_SETOR) VALUES ((SELECT ID FROM SIAAG.TAB_PONTO_ATENDIMENTO WHERE NOME = 'IGEPREV BELÉM'), (SELECT ID FROM SIAAG.TAB_SETOR WHERE DESCRICAO = 'Núcleo de Arrecadação Financeira'));
INSERT INTO SIAAG.TAB_PONTO_ATENDIMENTO_SETOR (ID_PONTO_ATENDIMENTO, ID_SETOR) VALUES ((SELECT ID FROM SIAAG.TAB_PONTO_ATENDIMENTO WHERE NOME = 'IGEPREV BELÉM'), (SELECT ID FROM SIAAG.TAB_SETOR WHERE DESCRICAO = 'Procuradoria Jurídica'));
INSERT INTO SIAAG.TAB_PONTO_ATENDIMENTO_SETOR (ID_PONTO_ATENDIMENTO, ID_SETOR) VALUES ((SELECT ID FROM SIAAG.TAB_PONTO_ATENDIMENTO WHERE NOME = 'IGEPREV BELÉM'), (SELECT ID FROM SIAAG.TAB_SETOR WHERE DESCRICAO = 'Diretoria de Administração e Finanças'));
INSERT INTO SIAAG.TAB_PONTO_ATENDIMENTO_SETOR (ID_PONTO_ATENDIMENTO, ID_SETOR) VALUES ((SELECT ID FROM SIAAG.TAB_PONTO_ATENDIMENTO WHERE NOME = 'IGEPREV BELÉM'), (SELECT ID FROM SIAAG.TAB_SETOR WHERE DESCRICAO = 'Gestão de Desenvolvimento de Pessoas'));
INSERT INTO SIAAG.TAB_PONTO_ATENDIMENTO_SETOR (ID_PONTO_ATENDIMENTO, ID_SETOR) VALUES ((SELECT ID FROM SIAAG.TAB_PONTO_ATENDIMENTO WHERE NOME = 'IGEPREV BELÉM'), (SELECT ID FROM SIAAG.TAB_SETOR WHERE DESCRICAO = 'Gerência de Orçamento e Finanças'));
INSERT INTO SIAAG.TAB_PONTO_ATENDIMENTO_SETOR (ID_PONTO_ATENDIMENTO, ID_SETOR) VALUES ((SELECT ID FROM SIAAG.TAB_PONTO_ATENDIMENTO WHERE NOME = 'IGEPREV BELÉM'), (SELECT ID FROM SIAAG.TAB_SETOR WHERE DESCRICAO = 'Gerência de Administração e Serviços'));
INSERT INTO SIAAG.TAB_PONTO_ATENDIMENTO_SETOR (ID_PONTO_ATENDIMENTO, ID_SETOR) VALUES ((SELECT ID FROM SIAAG.TAB_PONTO_ATENDIMENTO WHERE NOME = 'IGEPREV BELÉM'), (SELECT ID FROM SIAAG.TAB_SETOR WHERE DESCRICAO = 'Núcleo de Tecnologia de Informação'));
INSERT INTO SIAAG.TAB_PONTO_ATENDIMENTO_SETOR (ID_PONTO_ATENDIMENTO, ID_SETOR) VALUES ((SELECT ID FROM SIAAG.TAB_PONTO_ATENDIMENTO WHERE NOME = 'IGEPREV BELÉM'), (SELECT ID FROM SIAAG.TAB_SETOR WHERE DESCRICAO = 'Diretoria de Previdência'));
INSERT INTO SIAAG.TAB_PONTO_ATENDIMENTO_SETOR (ID_PONTO_ATENDIMENTO, ID_SETOR) VALUES ((SELECT ID FROM SIAAG.TAB_PONTO_ATENDIMENTO WHERE NOME = 'IGEPREV BELÉM'), (SELECT ID FROM SIAAG.TAB_SETOR WHERE DESCRICAO = 'Gerência de Cadastro e Habilitação'));
INSERT INTO SIAAG.TAB_PONTO_ATENDIMENTO_SETOR (ID_PONTO_ATENDIMENTO, ID_SETOR) VALUES ((SELECT ID FROM SIAAG.TAB_PONTO_ATENDIMENTO WHERE NOME = 'IGEPREV BELÉM'), (SELECT ID FROM SIAAG.TAB_SETOR WHERE DESCRICAO = 'Gerência de Concessão de Benefício'));
INSERT INTO SIAAG.TAB_PONTO_ATENDIMENTO_SETOR (ID_PONTO_ATENDIMENTO, ID_SETOR) VALUES ((SELECT ID FROM SIAAG.TAB_PONTO_ATENDIMENTO WHERE NOME = 'IGEPREV BELÉM'), (SELECT ID FROM SIAAG.TAB_SETOR WHERE DESCRICAO = 'Núcleo de Registro de Contribuições'));
INSERT INTO SIAAG.TAB_PONTO_ATENDIMENTO_SETOR (ID_PONTO_ATENDIMENTO, ID_SETOR) VALUES ((SELECT ID FROM SIAAG.TAB_PONTO_ATENDIMENTO WHERE NOME = 'IGEPREV BELÉM'), (SELECT ID FROM SIAAG.TAB_SETOR WHERE DESCRICAO = 'Serviço Social'));
INSERT INTO SIAAG.TAB_PONTO_ATENDIMENTO_SETOR (ID_PONTO_ATENDIMENTO, ID_SETOR) VALUES ((SELECT ID FROM SIAAG.TAB_PONTO_ATENDIMENTO WHERE NOME = 'IGEPREV BELÉM'), (SELECT ID FROM SIAAG.TAB_SETOR WHERE DESCRICAO = 'Núcleo de Diligências'));
INSERT INTO SIAAG.TAB_PONTO_ATENDIMENTO_SETOR (ID_PONTO_ATENDIMENTO, ID_SETOR) VALUES ((SELECT ID FROM SIAAG.TAB_PONTO_ATENDIMENTO WHERE NOME = 'IGEPREV BELÉM'), (SELECT ID FROM SIAAG.TAB_SETOR WHERE DESCRICAO = 'Arquivo Geral'));
INSERT INTO SIAAG.TAB_PONTO_ATENDIMENTO_SETOR (ID_PONTO_ATENDIMENTO, ID_SETOR) VALUES ((SELECT ID FROM SIAAG.TAB_PONTO_ATENDIMENTO WHERE NOME = 'IGEPREV BELÉM'), (SELECT ID FROM SIAAG.TAB_SETOR WHERE DESCRICAO = 'Protocolo'));

INSERT INTO SIAAG.TAB_PESSOA(CELULAR, CPF, DATA_NASCIMENTO, EMAIL, NOME, TELEFONE1, TELEFONE2, ID_ENDERECO) VALUES ('9199999999', '82826844300', '01/01/2000', 'admin@techlead.com.br', 'Administrador Techlead', '9199999999', '9199999999', (SELECT ID FROM SIAAG.TAB_ENDERECO WHERE CEP = '66055200' AND NUMERO = '1476'));

INSERT INTO SIAAG.TAB_USUARIO (ATIVO, LOGIN, SENHA, ID_PERFIL, ID_PESSOA, PRIMEIRO_ACESSO, ID_PONTO_ATENDIMENTO_SETOR, MATRICULA) VALUES (1, '82826844300', '$2a$10$L.ExqQjpsYJJK6tS.98AdOEYnhwsCuhH1uIQ/k38uIVOJ7pdrJLZC', 1, (SELECT ID FROM SIAAG.TAB_PESSOA WHERE CPF = '82826844300'), 0, (SELECT MIN(ID) FROM SIAAG.TAB_PONTO_ATENDIMENTO_SETOR), null);