begin BEGIN EXECUTE IMMEDIATE 'drop table SIAAG.TAB_ATENDIMENTO  cascade constraints';EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(SQLCODE||' -ERROR- '||SQLERRM);  END;end;
/
begin BEGIN EXECUTE IMMEDIATE 'drop table SIAAG.TAB_SITUACAO_ATENDIMENTO  cascade constraints';EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(SQLCODE||' -ERROR- '||SQLERRM);  END;end;
/
begin BEGIN EXECUTE IMMEDIATE 'drop table SIAAG.TAB_TIPO_ATENDIMENTO  cascade constraints';EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(SQLCODE||' -ERROR- '||SQLERRM);  END;end;
/
begin BEGIN EXECUTE IMMEDIATE 'drop table SIAAG.TAB_PONTO_ATENDIMENTO  cascade constraints';EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(SQLCODE||' -ERROR- '||SQLERRM);  END;end;
/