CREATE TABLE "SIAAG"."TAB_TIPO_ATENDIMENTO" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE  NOT NULL ENABLE, 
	"DESCRICAO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"TEMPO_ATENDIMENTO" NUMBER(2,0) NOT NULL ENABLE, 
	"TEMPO_ANALISE" NUMBER(2,0) NOT NULL ENABLE, 
	"REDIRECIONAMENTO" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"ATIVO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	 CONSTRAINT "PK_TIPO_ATENDIMENTO" PRIMARY KEY ("ID"))
/
  
  
DELETE FROM SIAAG.TAB_TIPO_ATENDIMENTO
/
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO(DESCRICAO,TEMPO_ATENDIMENTO,TEMPO_ANALISE,REDIRECIONAMENTO) VALUES ('PENSÃO',30,0,0)
/
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO(DESCRICAO,TEMPO_ATENDIMENTO,TEMPO_ANALISE,REDIRECIONAMENTO) VALUES ('REVISÃO DE PENSÃO',30,0,0)
/
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO(DESCRICAO,TEMPO_ATENDIMENTO,TEMPO_ANALISE,REDIRECIONAMENTO) VALUES ('REVISÃO DE APOSENTADORIA',30,0,0)
/
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO(DESCRICAO,TEMPO_ATENDIMENTO,TEMPO_ANALISE,REDIRECIONAMENTO) VALUES ('REVISÃO DE RESERVA/ REFORMA',30,0,0)
/
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO(DESCRICAO,TEMPO_ATENDIMENTO,TEMPO_ANALISE,REDIRECIONAMENTO) VALUES ('AUXÍLIO-FUNERAL',30,0,0)
/
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO(DESCRICAO,TEMPO_ATENDIMENTO,TEMPO_ANALISE,REDIRECIONAMENTO) VALUES ('ISENÇÃO DE IMPOSTO DE RENDA',30,0,0)
/
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO(DESCRICAO,TEMPO_ATENDIMENTO,TEMPO_ANALISE,REDIRECIONAMENTO) VALUES ('CERTIDÃO DE TEMPO DE CONTRIBUIÇÃO',30,0,0)
/
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO(DESCRICAO,TEMPO_ATENDIMENTO,TEMPO_ANALISE,REDIRECIONAMENTO) VALUES ('INCLUSÃO DE DEPENDENTES',30,0,0)
/
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO(DESCRICAO,TEMPO_ATENDIMENTO,TEMPO_ANALISE,REDIRECIONAMENTO) VALUES ('SOLICITAÇÃO DE COPIA DE PROCESSO',30,0,0)
/
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO(DESCRICAO,TEMPO_ATENDIMENTO,TEMPO_ANALISE,REDIRECIONAMENTO) VALUES ('SOLICITAÇÃO DE DECLARAÇÃO DE R. DE P.A',30,0,0)
/
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO(DESCRICAO,TEMPO_ATENDIMENTO,TEMPO_ANALISE,REDIRECIONAMENTO) VALUES ('COMUNICADO DE OBITO ',30,0,0)
/
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO(DESCRICAO,TEMPO_ATENDIMENTO,TEMPO_ANALISE,REDIRECIONAMENTO) VALUES ('LIBERAÇÃO/ CADASTRO C/C P/ PAGAMENTO',30,0,0)
/
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO(DESCRICAO,TEMPO_ATENDIMENTO,TEMPO_ANALISE,REDIRECIONAMENTO) VALUES ('APOSENTADORIA', 30, 0, 0)
/
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO(DESCRICAO,TEMPO_ATENDIMENTO,TEMPO_ANALISE,REDIRECIONAMENTO) VALUES ('RESERVA/ REFORMA', 30, 0, 0)
/
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO(DESCRICAO,TEMPO_ATENDIMENTO,TEMPO_ANALISE,REDIRECIONAMENTO) VALUES ('CERTIDÃO NEGATIVA', 30, 0, 0)
/
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO(DESCRICAO,TEMPO_ATENDIMENTO,TEMPO_ANALISE,REDIRECIONAMENTO) VALUES ('DECLARAÇÃO DE DEPENDENTES', 30, 0, 0)
/
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO(DESCRICAO,TEMPO_ATENDIMENTO,TEMPO_ANALISE,REDIRECIONAMENTO) VALUES ('2ª VIA CONTRA-CHEQUE', 30, 0, 0)
/
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO(DESCRICAO,TEMPO_ATENDIMENTO,TEMPO_ANALISE,REDIRECIONAMENTO) VALUES ('2ª VIA CÉDULA C', 30, 0, 0)
/
INSERT INTO SIAAG.TAB_TIPO_ATENDIMENTO(DESCRICAO,TEMPO_ATENDIMENTO,TEMPO_ANALISE,REDIRECIONAMENTO) VALUES ('ATUALIZAÇÃO DE ENDEREÇO', 30, 0, 0)
/