begin BEGIN EXECUTE IMMEDIATE 'drop table SIAAG.TAB_PONTO_ATENDIMENTO  cascade constraints';EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(SQLCODE||' -ERROR- '||SQLERRM);  END;end;
/
CREATE TABLE "SIAAG"."TAB_PONTO_ATENDIMENTO" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE, 
	"NOME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"ID_ENDERECO" NUMBER(10,0), 
	 CONSTRAINT "PK_PONTO_ATENDIMENTO" PRIMARY KEY ("ID"))
	 /
  
  DELETE FROM SIAAG.TAB_ENDERECO WHERE CEP = '66040020' AND NUMERO = '1982'
  /
  INSERT INTO SIAAG.TAB_ENDERECO(CEP,BAIRRO,CIDADE,LOGRADOURO,NUMERO,UF) VALUES ('66040020','Nazaré','Belém','Av. Alcindo Cacela','1982','PA')
  /

  DELETE FROM "SIAAG"."TAB_PONTO_ATENDIMENTO"
  /
  INSERT INTO "SIAAG"."TAB_PONTO_ATENDIMENTO"(NOME,ID_ENDERECO) VALUES ('IGEPREV BELÉM',(SELECT ID FROM SIAAG.TAB_ENDERECO WHERE CEP = '66040020' AND NUMERO = '1982' AND LOGRADOURO = 'Av. Alcindo Cacela'))
  /
  
  

