DELETE FROM "SIAAG"."TAB_TIPO_BENEFICIARIO"
/
INSERT INTO "SIAAG"."TAB_TIPO_BENEFICIARIO" (ID,DESCRICAO) VALUES (1,'Pensionista')
/
INSERT INTO "SIAAG"."TAB_TIPO_BENEFICIARIO" (ID,DESCRICAO) VALUES (2,'Público em geral')
/
INSERT INTO "SIAAG"."TAB_TIPO_BENEFICIARIO" (ID,DESCRICAO) VALUES (3,'Servidor ativo')
/
INSERT INTO "SIAAG"."TAB_TIPO_BENEFICIARIO" (ID,DESCRICAO) VALUES (4,'Servidor inativo')
/