ALTER TABLE SIAAG.TAB_ATENDIMENTO 
ADD (ID_USUARIO_CADASTROU NUMBER(10) NOT NULL);

ALTER TABLE SIAAG.TAB_ATENDIMENTO
ADD CONSTRAINT FK_ATENDIMENTO_USUARIO FOREIGN KEY
(
  ID_USUARIO_CADASTROU 
)
REFERENCES SIAAG.TAB_USUARIO
(
  ID 
)
ENABLE;

ALTER TABLE SIAAG.TAB_ATENDIMENTO ADD senha NUMBER(10) NULL;
COMMENT ON COLUMN SIAAG.TAB_ATENDIMENTO.senha IS 'Senha do atendimento.';

ALTER TABLE SIAAG.TAB_ATENDIMENTO
ADD CONSTRAINT FK_ATENDIMENTO_TP_ATEND
FOREIGN KEY (ID_TIPO_ATENDIMENTO) REFERENCES SIAAG.TAB_TIPO_ATENDIMENTO (ID);